package org.monarchinitiative.hpoannotqc.annotations.hpoaerror;

public enum HpoaErrorCategory {
    EMPTY_DISEASE_NAME,
    INVALID_FRACTION,
    INVALID_FREQUENCY_TERM,
    INVALID_MODIFIER_TERMID,
    INVALID_SUBONTOLOGY,
    INVALID_PERCENTAGE,
    MALFORMED_BIOCURATION_ENTRY,
    MALFORMED_FREQUENCY_STRING,
    MALFORMED_NEGATION,
    MALFORMED_SEX_STRING,
    MALFORMED_TERM_ID,
    MISSING_LABEL,
    OBSOLETE_TERM_LABEL,
    OBSOLETE_TERM_ID,
    OMIT_FILE_ERROR,
    TERM_ID_NOT_IN_ONTOLOGY
}
